### ISSUE TITLE
AttributeError: 'SemiSupervisor' object has no attribute 'annotate'

### ISSUE THREAD

**Issue by arturOA** [janfreyberg/superintendent#31]
Hi, 

I am trying to run the examples you have and I am running into this error: 

`AttributeError: 'SemiSupervisor' object has no attribute 'annotate'`

When running 

`labelling_widget.annotate(options=['professional', 'not professional'])`

This was working when you ran the tutorial in ODSC London... I tried it today and it is not working anymore...

**Comment by janfreyberg** [comment]
Hi Artur,

this interaface has recently changed - you now don't call `annotate` anymore, you simply display the widget at the end of a jupyter cell:

```python
from superintendent import SemiSupervisor
import pandas as pd
from IPython import display

labelling_widget = SemiSupervisor(
    headlines,
    options=['professional', 'not professional'],
)

labelling_widget
```

I haven't updated the documentation yet for this, apologies

**Comment by arturOA** [comment]
Thanks, @janfreyberg !

This fixes the problem :+1:

**Comment by janfreyberg** [comment]
Great! I'll keep this issue open until I actually update the documentation.
