### ISSUE TITLE
Possibilities to display multiple assisting images when labelling the target image

### ISSUE THREAD

**Issue by shexiaogui** [janfreyberg/superintendent#57]
We have a labelling task that the labellers need to look at 4 to 5 similar images under the same folder and compare these images with the one that she/he really want to label. 

Is this possible with superintendent and how to do this.

**Comment by janfreyberg** [comment]
Interesting - so is your folder structure like this:

```
|
|-example_1
|    |-target_image.jpg
|    |-reference_image_1.jpg
|    |-reference_image_2.jpg
|    |-reference_image_3.jpg
|-example_2
|    |-target_image.jpg
|    |-reference_image_1.jpg
|    |-reference_image_2.jpg
|    |-reference_image_3.jpg
```

Or are the reference images the same for all examples?

**Comment by shexiaogui** [comment]
It looks like this:
```
|
|-example_1
|    |-img_1.jpg
|    |-img_2.jpg
|    |-img_3.jpg
|    |-img_4.jpg
|-example_2
|    |-img_1.jpg
|    |-img_2.jpg
|    |-img_3.jpg
|    |-img_4.jpg
```
When you label `example_1/img_1.jpg`, the `img_2.jpg`  to `img_4.jpg` under the same folder are the reference images. 
Then you finished labelling `img_1.jpg` and move to `img_2.jpg`. Now img_1, 3 and 4 are your reference images. And it goes on.

Another possibilities is to display all images under `example_1` and under each image has its own labelling widgets. The point is to let labeller to see everything under `example_1` when she/he labels its images.

**Comment by janfreyberg** [comment]
How about something like this:

```python
import pathlib
import superintendent
import ipywidgets as widgets
from IPython.display import display

images = [f for f in pathlib.Path("example/").glob("**/*") if f.is_file()]
print(images)

def display_image_and_references(image_path):
    image_folder = image_path.parent
    other_images = [
        f for f in image_folder.glob("*")
        if f.is_file() and f != image_path
    ]
    image_display = widgets.VBox([
        widgets.Image(value=image_path.read_bytes()),
        widgets.HBox(
            [
                widgets.VBox([
                    widgets.Label(f"Image {i}"),
                    widgets.Image(value=image.read_bytes()),
                ])
                for i, image in enumerate(other_images)
            ]
        ),
    ])
    display(image_display)

labeller = superintendent.ClassLabeller(
    features=images,
    options=[f"image {i}" for i in range(5)],
    display_func=display_image_and_references,
)

labeller
```

This looks like this for me:

![image](https://user-images.githubusercontent.com/4092425/82382768-7c1d0c00-9a24-11ea-9c86-b3178c4a9a4d.png)

**Comment by shexiaogui** [comment]
The example is very helpful! Thanks Jan

**Comment by janfreyberg** [comment]
I'm glad you're using it! Let me know how it goes.
